# Generated by Django 4.2 on 2023-05-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
