# Generated by Django 4.2 on 2023-05-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_dbmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
